import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BottomTabs from "@/components/BottomTabs";

export const metadata: Metadata = {
  title: "Wafiyat Clone",
  description: "Generated by create next app",
};

const almarai = Almarai({
  weight: ["300", "400", "700", "800"],
  subsets: ["arabic", "latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={almarai.className}>
        <Navbar />
        <main>{children}</main>
        <BottomTabs />
      </body>
    </html>
  );
}
