import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Wafiyat Clone",
  description: "Generated by create next app",
};

const almarai = Almarai({
  weight: ["300", "400", "700", "800"],
  subsets: ["arabic", "latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={almarai.className}>{children}</body>
    </html>
  );
}
